# Generated by Django 6.0 on 2026-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_CodeForFuture', '0002_hackathon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('certificate', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='course_logos/')),
            ],
        ),
    ]
