# Generated by Django 6.0 on 2026-03-15 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_CodeForFuture', '0003_freecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecourse',
            options={'ordering': ['title'], 'verbose_name': 'Free Course', 'verbose_name_plural': 'Free Courses'},
        ),
        migrations.AddField(
            model_name='freecourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freecourse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='freecourse',
            name='duration',
            field=models.CharField(help_text='Example: 3 hours / 4 weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='freecourse',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='course_logos/'),
        ),
        migrations.AlterField(
            model_name='freecourse',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags like: AI, Python, ML', max_length=200),
        ),
    ]
