# Generated by Django 6.0 on 2026-03-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_CodeForFuture', '0004_alter_freecourse_options_freecourse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Free Course', 'verbose_name_plural': 'Free Courses'},
        ),
    ]
